image: alpine/edge
packages:
  - editorconfig-checker
  - icu-dev
  - jq
  - linux-headers
  - pnc
  - scd2html
  - scdoc
  - shellcheck
  - shellspec
sources:
  - https://git.sr.ht/~mil/sxmo-utils
submitter:
  hub.sr.ht:
    enabled: false
  git.sr.ht:
    enabled: true
    allow-refs:
      - refs/heads/master
      - "refs/tags/*"
triggers:
  - action: email
    condition: failure
    to: "~mil/sxmo-devel@lists.sr.ht"
tasks:
  - environment: |
      cd sxmo-utils
      if [ "$(git remote get-url origin)" != "https://git.sr.ht/~mil/sxmo-utils" ]
      then
        complete-build
      fi
  - test: |
      cd sxmo-utils
      make test
  - build-doc: |
      cd sxmo-utils
      make docs
      make html-docs
