#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super+Shift Return spawn 'foot'

# Super+Q to close the focused view
riverctl map normal Super+Shift Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a menu mode, like in sway, to use vol up/down and power when navigating in menus.
riverctl declare-mode menu
riverctl map menu None XF86PowerOff spawn "wtype -k Return"
riverctl map menu None XF86AudioRaiseVolume spawn "wtype -k Up"
riverctl map menu None XF86AudioLowerVolume spawn "wtype -k Down"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Drop this when bonsai is available on 32 bits systems
multikey_retrocompat() {
	sxmo_multikey.sh clear
	for mode in normal locked
	do
		riverctl map $mode None XF86PowerOff spawn "sxmo_multikey.sh \
			powerbutton \
			powerbutton_one \
			powerbutton_two \
			powerbutton_three"
		riverctl map $mode None XF86AudioRaiseVolume spawn \
			"sxmo_multikey.sh \
			volup \
			volup_one \
			volup_two \
			volup_three"
		riverctl map $mode None XF86AudioLowerVolume spawn \
			"sxmo_multikey.sh \
			voldown \
			voldown_one \
			voldown_two \
			voldown_three"
	done
}

if ! command -v bonsaictl > /dev/null; then
	multikey_retrocompat
else
	for mode in normal locked
	do
		riverctl map $mode None XF86PowerOff spawn \
			"bonsaictl -e power_pressed"
		riverctl map -release $mode None XF86PowerOff spawn \
			"bonsaictl -e power_released"

		riverctl map $mode None XF86AudioRaiseVolume spawn \
			"bonsaictl -e volup_pressed"
		riverctl map -release $mode None XF86AudioRaiseVolume spawn \
			"bonsaictl -e volup_released"

		riverctl map $mode None XF86AudioLowerVolume spawn \
			"bonsaictl -e voldown_pressed"
		riverctl map -release $mode None XF86AudioLowerVolume spawn \
			"bonsaictl -e voldown_released"
	done
fi

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    #riverctl map $mode None XF86AudioRaiseVolume  spawn 'sxmo_audio.sh vol up'
    #riverctl map $mode None XF86AudioLowerVolume  spawn 'sxmo_audio.sh vol down'
    riverctl map $mode None XF86AudioMute         spawn 'sxmo_audio.sh vol togglemute'
    riverctl map $mode None XF86AudioMicMute      spawn 'sxmo_audio.sh mic togglemute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'sxmo_brightness.sh up'
    riverctl map $mode None XF86MonBrightnessDown spawn 'sxmo_brightness.sh down'

    riverctl map-switch $mode lid open spawn 'sxmo_wm.sh display on'
    riverctl map-switch $mode lid close spawn 'sxmo_wm.sh display off'
done

# Launch appmenu
riverctl map normal Super P spawn 'sxmo_appmenu.sh'
riverctl map normal Super+Shift P spawn 'sxmo_appmenu.sh sys'

# Start your launcher
riverctl map normal Super D spawn 'bemenu-run'

# Manual locker
riverctl map normal Super G spawn 'sxmo_state.sh set locker'

# Shutdown
riverctl map normal Super T spawn 'sxmo_appmenu.sh power'

# Set background and border color
riverctl background-color 0x282a36
riverctl border-color-focused 0xff4971
riverctl border-color-unfocused 0x282a36

# Set keyboard repeat rate
riverctl set-repeat 40 400

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &

riverctl focus-follows-cursor normal
riverctl border-width 3

exec sxmo_hook_start.sh
